# Find out more about tasks: http://docs.devo.ps/manual/tasks

id: install_ghost
name: Install ghost
type: task

targets:
  - ansbotanics

vars:
  build: /opt/ghost
  domain: ansbotanics.com

steps:
  - run: sudo apt-get install zip unzip
  - run: curl -L https://ghost.org/zip/ghost-latest.zip -o ghost.zip
  - run: sudo unzip -uo ghost.zip -d {{build}}
  - run: cd {{build}} && sudo npm install --production
  - run: cd {{build}} && NODE_ENV=production forever start index.js
 